2019-08-08 12:47:21,124 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 12:48:02,926 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 12:48:07,493 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 12:48:09,562 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 12:51:55,004 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 12:59:11,785 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:00:31,237 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:01:36,990 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:01:44,455 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:04:06,810 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:06:24,406 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:07:34,162 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:11:23,082 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:14:14,568 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:14:50,362 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:20:41,501 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:27:40,435 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:28:23,583 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:28:28,316 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 13:30:07,215 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 23:41:34,866 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-08 23:41:38,131 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
2019-08-09 00:29:09,006 [ERROR]  Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic/app.py", line 958, in handle_request
    request, response
  File "/home/abwao/.local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/home/abwao/.local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'list' object has no attribute 'headers'
